
// src/lib/app-builder/flutter-gen/index.js

/**
 * Convert hex color to 0xFF...
 */
const toColor = (hex) => {
  if (!hex) return "0xFF000000";
  return "0xFF" + hex.replace("#", "");
};

/**
 * Generate pubspec.yaml
 */
const generatePubspec = (config) => {
  return `name: appforge_app
description: Generated by EventForge App Builder
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.4
  http: ^1.2.0
  share_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
`;
};

/**
 * Generate GitHub Action Workflow (Build APK)
 */
const generateWorkflow = (config) => {
  return `name: Build Android APK
on: [push]
jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
      
      - run: flutter pub get
      - run: flutter build apk --release --no-tree-shake-icons
      
      - uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
`;
};

const generateMain = (config) => {
  const firstScreen = config.screens[0];
  const screenId = firstScreen.id;
  
  // Generate imports for all screens
  const imports = config.screens.map(s => 
      `import 'screens/${s.id}_screen.dart';` 
  ).join('\n');

  // Generate routes map
  const routes = config.screens.map(s => {
      const cls = s.id.charAt(0).toUpperCase() + s.id.slice(1) + 'Screen';
      return `'/${s.id}': (context) => const ${cls}(),`;
  }).join('\n        ');

  return `import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'theme.dart';
${imports}

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: '${config.name}',
      debugShowCheckedModeBanner: false,
      theme: AppTheme.lightTheme,
      initialRoute: '/${screenId}',
      routes: {
        ${routes}
      },
    );
  }
}
`;
};

/**
 * Generate lib/theme.dart
 */
const generateTheme = (config) => {
  const t = config.theme || {};
  return `import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

class AppTheme {
  static const Color primary = Color(${toColor(t.primary_color)});
  static const Color secondary = Color(${toColor(t.secondary_color)});
  static const Color background = Color(${toColor(t.background_color)});
  static const Color surface = Color(${toColor(t.surface_color)});
  static const Color text = Color(${toColor(t.text_color)});

  static ThemeData get lightTheme => ThemeData(
    useMaterial3: true,
    scaffoldBackgroundColor: background,
    colorScheme: ColorScheme.light(
        primary: primary,
        secondary: secondary,
        surface: surface,
        onSurface: text,
    ),
    textTheme: GoogleFonts.${t.font_family?.toLowerCase() || 'inter'}TextTheme().apply(
        bodyColor: text,
        displayColor: text,
    ),
    appBarTheme: AppBarTheme(
        backgroundColor: surface,
        foregroundColor: text,
        elevation: 0,
    ),
  );
}
`;
};

/**
 * Render a single component to Dart code
 */
const renderComponent = (comp) => {
  const p = comp.props || {};
  
  switch(comp.type) {
    case 'text':
      return `Text(
        '${p.text}',
        style: TextStyle(
            fontSize: ${p.fontSize || 16},
            fontWeight: ${p.fontWeight === 'bold' ? 'FontWeight.bold' : 'FontWeight.normal'},
            color: ${p.color ? `Color(${toColor(p.color)})` : 'null'},
        ),
      ),SizedBox(height: 8),`;
      
    case 'button':
      // Connect onPressed to _handleAction
      const isAI = (p.action || "").startsWith('ai:');
      const childContent = isAI 
        ? `_loading ? const SizedBox(height: 20, width: 20, child: CircularProgressIndicator(strokeWidth: 2, color: Colors.white)) : Text('${p.text}')`
        : `Text('${p.text}')`;

      return `SizedBox(
        width: ${p.fullWidth ? 'double.infinity' : 'null'},
        child: ElevatedButton(
            onPressed: ${isAI} && _loading ? null : () => _handleAction('${p.action || ""}'), 
            style: ElevatedButton.styleFrom(
                backgroundColor: AppTheme.primary,
                foregroundColor: Colors.white,
                padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 14),
                shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
            ),
            child: ${childContent},
        ),
      ),SizedBox(height: 12),`;

    case 'hero': // Maps to Image
    case 'image':
      return `ClipRRect(
        borderRadius: BorderRadius.circular(12),
        child: Image.network(
            '${p.url}',
            height: ${p.height || 200},
            width: double.infinity,
            fit: BoxFit.cover,
            errorBuilder: (c,e,s) => Container(height: 200, color: Colors.grey[800]),
        ),
      ),SizedBox(height: 12),`;
      
    case 'text_field':
      // Connect controller
      const controllerRef = comp.id ? `controller: _controllers['${comp.id}'],` : '';
      return `TextField(
        ${controllerRef}
        decoration: InputDecoration(
            labelText: '${p.label}',
            hintText: '${p.hint}',
            filled: true,
            fillColor: AppTheme.surface,
            border: OutlineInputBorder(borderRadius: BorderRadius.circular(12)),
        ),
        obscureText: ${p.obscure ? 'true' : 'false'},
        maxLines: ${p.multiline ? 5 : 1},
      ),SizedBox(height: 16),`;

    case 'list_tile':
        return `ListTile(
            tileColor: AppTheme.surface,
            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
            leading: const Icon(Icons.${p.icon || 'star'}, color: AppTheme.primary),
            title: Text('${p.title}'),
            subtitle: Text('${p.subtitle}'),
            trailing: const Icon(Icons.chevron_right),
            onTap: () {},
        ),SizedBox(height: 8),`;

    case 'row':
        return `Row(
            spacing: 8,
            children: [
                ${(comp.children || []).map(c => 
                    // Recursively render children in row. Note: Row children usually need Expanded or Flexible if button
                    c.type === 'button' ? 'Expanded(child: ' + renderComponent(c).replace(',SizedBox(height: 12),', '') + ')' 
                    : renderComponent(c).replace(',SizedBox(height: 12),', '')
                ).join(',\n')}
            ],
        ),SizedBox(height: 12),`;

    case 'divider':
        return `const Divider(),SizedBox(height: 12),`;

    case 'app_bar':
        // Handled in Scaffold, not body
        return '';

    default:
      return `// Unknown: ${comp.type}`;
  }
};

const generateScreen = (screen, config) => {
    // Check if we need controllers (if text_fields exist)
    const hasTextFields = screen.components.some(c => c.type === 'text_field');
    const importServices = `import 'package:flutter/services.dart';`;

    const bodyWidgets = screen.components
        .filter(c => c.type !== 'app_bar')
        .map(renderComponent)
        .join("\n              ");

    const appBarComp = screen.components.find(c => c.type === 'app_bar');
    const appBarCode = appBarComp 
        ? `appBar: AppBar(title: Text('${appBarComp.props.title}'), centerTitle: ${appBarComp.props.centered}),`
        : '';

    const className = screen.id.charAt(0).toUpperCase() + screen.id.slice(1) + 'Screen';

    return `import 'package:flutter/material.dart';
import '../theme.dart';
import 'package:http/http.dart' as http;
import 'dart:convert';
import 'package:share_plus/share_plus.dart';
${importServices}

class ${className} extends StatefulWidget {
  const ${className}({super.key});

  @override
  State<${className}> createState() => _${className}State();
}

class _${className}State extends State<${className}> {
  final Map<String, TextEditingController> _controllers = {};
  bool _loading = false;

  @override
  void initState() {
    super.initState();
    // Initialize controllers for text fields
    ${screen.components.filter(c => c.type === 'text_field').map(c => 
        `_controllers['${c.id}'] = TextEditingController();`
    ).join('\n    ')}
  }

  @override
  void dispose() {
    _controllers.forEach((_, controller) => controller.dispose());
    super.dispose();
  }

  Future<void> _handleAction(String action) async {
    if (action.startsWith('navigate:')) {
      // Navigate to route
      final target = action.split(':')[1];
      Navigator.pushNamed(context, '/$target');
    } else if (action.startsWith('share:')) {
      // Smart Share: Try to find 'output' field, else default
      String textToShare = "Check out my event!";
      if (_controllers.containsKey('output')) {
          textToShare = _controllers['output']!.text;
      }
      Share.share(textToShare);
    } else if (action.startsWith('copy:')) {
      // Smart Copy: Try to find 'output' field, else default
      String textToCopy = "Copied Content";
      if (_controllers.containsKey('output')) {
          textToCopy = _controllers['output']!.text;
      }
      
      Clipboard.setData(ClipboardData(text: textToCopy));
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Copied to clipboard!')),
      );
    } else if (action.startsWith('save_form:')) {
      // Collect data
      final data = _controllers.map((key, controller) => MapEntry(key, controller.text));
      // Show confirmation
      showDialog(
        context: context,
        builder: (context) => AlertDialog(
          title: const Text('Form Submitted'),
          content: Text('Data: $data'),
          actions: [
            TextButton(
              onPressed: () => Navigator.pop(context),
              child: const Text('OK'),
            ),
          ],
        ),
      );
    } else if (action.startsWith('ai:')) {
       setState(() => _loading = true);
       final type = action.split(':')[1].split('_')[1]; // e.g. generate_announcement -> announcement
       
       // Collect all form data
       final data = _controllers.map((key, controller) => MapEntry(key, controller.text));
       
       try {
         final url = Uri.parse('http://10.0.2.2:3000/api/ai-proxy');
         final response = await http.post(
            url, 
            headers: {'Content-Type': 'application/json'},
            body: jsonEncode({'type': type, 'data': data}),
         );

         if (response.statusCode == 200) {
             final result = jsonDecode(response.body)['result'];
             if (_controllers.containsKey('output')) {
                 _controllers['output']!.text = result;
             }
             if (mounted) {
               ScaffoldMessenger.of(context).showSnackBar(
                 const SnackBar(content: Text('AI Content Generated!')),
               );
             }
         } else {
             throw Exception('Failed to load AI response');
         }
       } catch (e) {
         if (mounted) {
            showDialog(
                context: context, 
                builder: (c) => AlertDialog(title: const Text('Error'), content: Text(e.toString()), actions: [TextButton(onPressed: () => Navigator.pop(c), child: const Text('OK'))])
            );
         }
       } finally {
         setState(() => _loading = false);
       }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      ${appBarCode}
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16),
        child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              ${bodyWidgets}
            ],
        ),
      ),
    );
  }
}
`;
};

/**
 * MAIN EXPORT
 * Returns a map of filenames to content
 */
export const generateFlutterProject = (config) => {
  const files = {};

  // Root
  files['pubspec.yaml'] = generatePubspec(config);
  files['README.md'] = `# ${config.name}\nGenerated by EventForge.`;
  files['.github/workflows/build.yml'] = generateWorkflow(config);

  // Lib
  files['lib/main.dart'] = generateMain(config);
  files['lib/theme.dart'] = generateTheme(config);

  // Screens
  config.screens.forEach(screen => {
      const filename = `lib/screens/${screen.id}_screen.dart`;
      files[filename] = generateScreen(screen, config);
  });

  return files;
};
